<?php
    // starting the session
    session_start();

    // analytics tracking
    include_once("analyticstracking.php");

    // connect to the database
    $db = mysqli_connect("db0.stevens.edu","w3_visdec","J9r1CbDR","w3_visdec"); 

    if (mysqli_connect_errno()) {
    echo printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }

    $t = microtime(true);
    $micro = sprintf("%06d",($t - floor($t)) * 1000000);
    $d = new DateTime( date('Y-m-d H:i:s.'.$micro, $t) );

    if (isset($_POST['Submit'])) { 
    $_SESSION['FeelHappyAfter'] = $_POST['radioHappyAfter'];
    $_SESSION['FeelSadAfter'] = $_POST['radioSadAfter'];
    $_SESSION['FeelAngryAfter'] = $_POST['radioAngryAfter'];
    $_SESSION['FeelScaredAfter'] = $_POST['radioScaredAfter'];
    $_SESSION['FeelSurprisedAfter'] = $_POST['radioSurprisedAfter'];
    $_SESSION['tsSubmitMoodAfter'] = $d->format("Y-m-d H:i:s.u");
    } 

    $sql="INSERT INTO responses (SessionID,
        Age,
        Gender,
        NativeSpeaker,
        FeelHappy,
        FeelSad,
        FeelAngry,
        FeelAfraid,
        FeelSurprised,
        HappyOne,
        HappyOneTagged,
        HappyTwo,
        HappyTwoTagged,
        HappyThree,
        HappyThreeTagged,
        HappyFour,
        HappyFourTagged,
        HappyFive,
        HappyFiveTagged,
        HappySix,
        HappySixTagged,
        HappySeven,
        HappySevenTagged,
        HappyEight,
        HappyEightTagged,
        SadOne,
        SadOneTagged,
        SadTwo,
        SadTwoTagged,
        SadThree,
        SadThreeTagged,
        SadFour,
        SadFourTagged,
        SadFive,
        SadFiveTagged,
        SadSix,
        SadSixTagged,
        SadSeven,
        SadSevenTagged,
        SadEight,
        SadEightTagged,
        AngryOne,
        AngryOneTagged,
        AngryTwo,
        AngryTwoTagged,
        AngryThree,
        AngryThreeTagged,
        AngryFour,
        AngryFourTagged,
        AngryFive,
        AngryFiveTagged,
        AngrySix,
        AngrySixTagged,
        AngrySeven,
        AngrySevenTagged,
        AngryEight,
        AngryEightTagged,
        AfraidOne,
        AfraidOneTagged,
        AfraidTwo,
        AfraidTwoTagged,
        AfraidThree,
        AfraidThreeTagged,
        AfraidFour,
        AfraidFourTagged,
        AfraidFive,
        AfraidFiveTagged,
        AfraidSix,
        AfraidSixTagged,
        AfraidSeven,
        AfraidSevenTagged,
        AfraidEight,
        AfraidEightTagged,
        SurprisedOne,
        SurprisedOneTagged,
        SurprisedTwo,
        SurprisedTwoTagged,
        SurprisedThree,
        SurprisedThreeTagged,
        SurprisedFour,
        SurprisedFourTagged,
        SurprisedFive,
        SurprisedFiveTagged,
        SurprisedSix,
        SurprisedSixTagged,
        SurprisedSeven,
        SurprisedSevenTagged,
        SurprisedEight,
        SurprisedEightTagged,
        NotHappyOne,
        NotHappyOneTagged,
        NotHappyTwo,
        NotHappyTwoTagged,
        NotHappyThree,
        NotHappyThreeTagged,
        NotHappyFour,
        NotHappyFourTagged,
        NotHappyFive,
        NotHappyFiveTagged,
        NotHappySix,
        NotHappySixTagged,
        NotHappySeven,
        NotHappySevenTagged,
        NotHappyEight,
        NotHappyEightTagged,
        NotSadOne,
        NotSadOneTagged,
        NotSadTwo,
        NotSadTwoTagged,
        NotSadThree,
        NotSadThreeTagged,
        NotSadFour,
        NotSadFourTagged,
        NotSadFive,
        NotSadFiveTagged,
        NotSadSix,
        NotSadSixTagged,
        NotSadSeven,
        NotSadSevenTagged,
        NotSadEight,
        NotSadEightTagged,
        FeelHappyAfter,
        FeelSadAfter,
        FeelAngryAfter,
        FeelAfraidAfter,
        FeelSurprisedAfter,
        tsBegin,
        tsSubmitBasics,
        tsSubmitMoodBefore,
        tsSubmitHappy,
        tsSubmitSad,
        tsSubmitAngry,
        tsSubmitScared,
        tsSubmitSurprised,
        tsSubmitNotHappy,
        tsSubmitNotSad,
        tsSubmitMoodAfter) VALUES ('".$_SESSION['SessionID']."',
        '".$_SESSION['Age']."',
        '".$_SESSION['Gender']."',
        '".$_SESSION['NativeSpeaker']."',
        '".$_SESSION['FeelHappy']."',
        '".$_SESSION['FeelSad']."',
        '".$_SESSION['FeelAngry']."',
        '".$_SESSION['FeelScared']."',
        '".$_SESSION['FeelSurprised']."',
        '".$_SESSION['HappyOne']."',
        '".$_SESSION['HappyOneTagged']."',
        '".$_SESSION['HappyTwo']."',
        '".$_SESSION['HappyTwoTagged']."',
        '".$_SESSION['HappyThree']."',
        '".$_SESSION['HappyThreeTagged']."',
        '".$_SESSION['HappyFour']."',
        '".$_SESSION['HappyFourTagged']."',
        '".$_SESSION['HappyFive']."',
        '".$_SESSION['HappyFiveTagged']."',
        '".$_SESSION['HappySix']."',
        '".$_SESSION['HappySixTagged']."',
        '".$_SESSION['HappySeven']."',
        '".$_SESSION['HappySevenTagged']."',
        '".$_SESSION['HappyEight']."',
        '".$_SESSION['HappyEightTagged']."',
        '".$_SESSION['SadOne']."',
        '".$_SESSION['SadOneTagged']."',
        '".$_SESSION['SadTwo']."',
        '".$_SESSION['SadTwoTagged']."',
        '".$_SESSION['SadThree']."',
        '".$_SESSION['SadThreeTagged']."',
        '".$_SESSION['SadFour']."',
        '".$_SESSION['SadFourTagged']."',
        '".$_SESSION['SadFive']."',
        '".$_SESSION['SadFiveTagged']."',
        '".$_SESSION['SadSix']."',
        '".$_SESSION['SadSixTagged']."',
        '".$_SESSION['SadSeven']."',
        '".$_SESSION['SadSevenTagged']."',
        '".$_SESSION['SadEight']."',
        '".$_SESSION['SadEightTagged']."',
        '".$_SESSION['AngryOne']."',
        '".$_SESSION['AngryOneTagged']."',
        '".$_SESSION['AngryTwo']."',
        '".$_SESSION['AngryTwoTagged']."',
        '".$_SESSION['AngryThree']."',
        '".$_SESSION['AngryThreeTagged']."',
        '".$_SESSION['AngryFour']."',
        '".$_SESSION['AngryFourTagged']."',
        '".$_SESSION['AngryFive']."',
        '".$_SESSION['AngryFiveTagged']."',
        '".$_SESSION['AngrySix']."',
        '".$_SESSION['AngrySixTagged']."',
        '".$_SESSION['AngrySeven']."',
        '".$_SESSION['AngrySevenTagged']."',
        '".$_SESSION['AngryEight']."',
        '".$_SESSION['AngryEightTagged']."',
        '".$_SESSION['ScaredOne']."',
        '".$_SESSION['ScaredOneTagged']."',
        '".$_SESSION['ScaredTwo']."',
        '".$_SESSION['ScaredTwoTagged']."',
        '".$_SESSION['ScaredThree']."',
        '".$_SESSION['ScaredThreeTagged']."',
        '".$_SESSION['ScaredFour']."',
        '".$_SESSION['ScaredFourTagged']."',
        '".$_SESSION['ScaredFive']."',
        '".$_SESSION['ScaredFiveTagged']."',
        '".$_SESSION['ScaredSix']."',
        '".$_SESSION['ScaredSixTagged']."',
        '".$_SESSION['ScaredSeven']."',
        '".$_SESSION['ScaredSevenTagged']."',
        '".$_SESSION['ScaredEight']."',
        '".$_SESSION['ScaredEightTagged']."',
        '".$_SESSION['SurprisedOne']."',
        '".$_SESSION['SurprisedOneTagged']."',
        '".$_SESSION['SurprisedTwo']."',
        '".$_SESSION['SurprisedTwoTagged']."',
        '".$_SESSION['SurprisedThree']."',
        '".$_SESSION['SurprisedThreeTagged']."',
        '".$_SESSION['SurprisedFour']."',
        '".$_SESSION['SurprisedFourTagged']."',
        '".$_SESSION['SurprisedFive']."',
        '".$_SESSION['SurprisedFiveTagged']."',
        '".$_SESSION['SurprisedSix']."',
        '".$_SESSION['SurprisedSixTagged']."',
        '".$_SESSION['SurprisedSeven']."',
        '".$_SESSION['SurprisedSevenTagged']."',
        '".$_SESSION['SurprisedEight']."',
        '".$_SESSION['SurprisedEightTagged']."',
        '".$_SESSION['NotHappyOne']."',
        '".$_SESSION['NotHappyOneTagged']."',
        '".$_SESSION['NotHappyTwo']."',
        '".$_SESSION['NotHappyTwoTagged']."',
        '".$_SESSION['NotHappyThree']."',
        '".$_SESSION['NotHappyThreeTagged']."',
        '".$_SESSION['NotHappyFour']."',
        '".$_SESSION['NotHappyFourTagged']."',
        '".$_SESSION['NotHappyFive']."',
        '".$_SESSION['NotHappyFiveTagged']."',
        '".$_SESSION['NotHappySix']."',
        '".$_SESSION['NotHappySixTagged']."',
        '".$_SESSION['NotHappySeven']."',
        '".$_SESSION['NotHappySevenTagged']."',
        '".$_SESSION['NotHappyEight']."',
        '".$_SESSION['NotHappyEightTagged']."',
        '".$_SESSION['NotSadOne']."',
        '".$_SESSION['NotSadOneTagged']."',
        '".$_SESSION['NotSadTwo']."',
        '".$_SESSION['NotSadTwoTagged']."',
        '".$_SESSION['NotSadThree']."',
        '".$_SESSION['NotSadThreeTagged']."',
        '".$_SESSION['NotSadFour']."',
        '".$_SESSION['NotSadFourTagged']."',
        '".$_SESSION['NotSadFive']."',
        '".$_SESSION['NotSadFiveTagged']."',
        '".$_SESSION['NotSadSix']."',
        '".$_SESSION['NotSadSixTagged']."',
        '".$_SESSION['NotSadSeven']."',
        '".$_SESSION['NotSadSevenTagged']."',
        '".$_SESSION['NotSadEight']."',
        '".$_SESSION['NotSadEightTagged']."',
        '".$_SESSION['FeelHappyAfter']."',
        '".$_SESSION['FeelSadAfter']."',
        '".$_SESSION['FeelAngryAfter']."',
        '".$_SESSION['FeelScaredAfter']."',
        '".$_SESSION['FeelSurprisedAfter']."',
        '".$_SESSION['tsBegin']."',
        '".$_SESSION['tsSubmitBasics']."',
        '".$_SESSION['tsSubmitMoodBefore']."',
        '".$_SESSION['tsSubmitHappy']."',
        '".$_SESSION['tsSubmitSad']."',
        '".$_SESSION['tsSubmitAngry']."',
        '".$_SESSION['tsSubmitScared']."',
        '".$_SESSION['tsSubmitSurprised']."',
        '".$_SESSION['tsSubmitNotHappy']."',
        '".$_SESSION['tsSubmitNotSad']."',
        '".$_SESSION['tsSubmitMoodAfter']."')";

    if (mysqli_query($db, $sql)) {
        echo "";
    } else {
        echo "Error occurred: " . mysqli_error($db);
    }

?> 

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>FACES</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
    <br>
    <h1>Thank You for Participating!</h1>
</body>
<footer>
  <p>Written by: Joe Manfredonia
  <br>Contact information: <a href="mailto:jmanfred@stevens.edu">jmanfred@stevens.edu</a></p>
  <p>Face images provided from the 2010 Cohn-Kanade dataset (CK+) with permission from authors.</p>
  <p>Lucey, P., Cohn, J. F., Kanade, T., Saragih, J., Ambadar, Z., & Matthews, I. (2010). 
  <br> The extended Cohn–Kanade dataset (CK+): A complete dataset for action unit and emotion-specified expression. In CVPR Workshop on human communicative behavior analysis.</p>
</footer>
</html>