<?php
    // starting the session
    session_start();

    // connect to the database
    $db = mysqli_connect("127.0.0.1","rogueone","Pehseses1","faces"); 

    if (mysqli_connect_errno()) {
    echo printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
    }

    if (isset($_POST['Submit'])) { 
    $_SESSION['FeelHappyAfter'] = $_POST['radioHappyAfter'];
    $_SESSION['FeelSadAfter'] = $_POST['radioSadAfter'];
    $_SESSION['FeelAngryAfter'] = $_POST['radioAngryAfter'];
    $_SESSION['FeelScaredAfter'] = $_POST['radioScaredAfter'];
    $_SESSION['FeelSurprisedAfter'] = $_POST['radioSurprisedAfter'];
    } 

    $sql="INSERT INTO responses (Age,
        Gender,
        FeelHappy,
        FeelSad,
        FeelAngry,
        FeelAfraid,
        FeelSurprised,
        HappyOne,
        HappyOneTagged,
        HappyTwo,
        HappyTwoTagged,
        HappyThree,
        HappyThreeTagged,
        HappyFour,
        HappyFourTagged,
        HappyFive,
        HappyFiveTagged,
        HappySix,
        HappySixTagged,
        HappySeven,
        HappySevenTagged,
        HappyEight,
        HappyEightTagged,
        SadOne,
        SadOneTagged,
        SadTwo,
        SadTwoTagged,
        SadThree,
        SadThreeTagged,
        SadFour,
        SadFourTagged,
        SadFive,
        SadFiveTagged,
        SadSix,
        SadSixTagged,
        SadSeven,
        SadSevenTagged,
        SadEight,
        SadEightTagged,
        AngryOne,
        AngryOneTagged,
        AngryTwo,
        AngryTwoTagged,
        AngryThree,
        AngryThreeTagged,
        AngryFour,
        AngryFourTagged,
        AngryFive,
        AngryFiveTagged,
        AngrySix,
        AngrySixTagged,
        AngrySeven,
        AngrySevenTagged,
        AngryEight,
        AngryEightTagged,
        AfraidOne,
        AfraidOneTagged,
        AfraidTwo,
        AfraidTwoTagged,
        AfraidThree,
        AfraidThreeTagged,
        AfraidFour,
        AfraidFourTagged,
        AfraidFive,
        AfraidFiveTagged,
        AfraidSix,
        AfraidSixTagged,
        AfraidSeven,
        AfraidSevenTagged,
        AfraidEight,
        AfraidEightTagged,
        SurprisedOne,
        SurprisedOneTagged,
        SurprisedTwo,
        SurprisedTwoTagged,
        SurprisedThree,
        SurprisedThreeTagged,
        SurprisedFour,
        SurprisedFourTagged,
        SurprisedFive,
        SurprisedFiveTagged,
        SurprisedSix,
        SurprisedSixTagged,
        SurprisedSeven,
        SurprisedSevenTagged,
        SurprisedEight,
        SurprisedEightTagged,
        FeelHappyAfter,
        FeelSadAfter,
        FeelAngryAfter,
        FeelAfraidAfter,
        FeelSurprisedAfter) VALUES ('".$_SESSION['Age']."',
        '".$_SESSION['Gender']."',
        '".$_SESSION['FeelHappy']."',
        '".$_SESSION['FeelSad']."',
        '".$_SESSION['FeelAngry']."',
        '".$_SESSION['FeelScared']."',
        '".$_SESSION['FeelSurprised']."',
        '".$_SESSION['HappyOne']."',
        '".$_SESSION['HappyOneTagged']."',
        '".$_SESSION['HappyTwo']."',
        '".$_SESSION['HappyTwoTagged']."',
        '".$_SESSION['HappyThree']."',
        '".$_SESSION['HappyThreeTagged']."',
        '".$_SESSION['HappyFour']."',
        '".$_SESSION['HappyFourTagged']."',
        '".$_SESSION['HappyFive']."',
        '".$_SESSION['HappyFiveTagged']."',
        '".$_SESSION['HappySix']."',
        '".$_SESSION['HappySixTagged']."',
        '".$_SESSION['HappySeven']."',
        '".$_SESSION['HappySevenTagged']."',
        '".$_SESSION['HappyEight']."',
        '".$_SESSION['HappyEightTagged']."',
        '".$_SESSION['SadOne']."',
        '".$_SESSION['SadOneTagged']."',
        '".$_SESSION['SadTwo']."',
        '".$_SESSION['SadTwoTagged']."',
        '".$_SESSION['SadThree']."',
        '".$_SESSION['SadThreeTagged']."',
        '".$_SESSION['SadFour']."',
        '".$_SESSION['SadFourTagged']."',
        '".$_SESSION['SadFive']."',
        '".$_SESSION['SadFiveTagged']."',
        '".$_SESSION['SadSix']."',
        '".$_SESSION['SadSixTagged']."',
        '".$_SESSION['SadSeven']."',
        '".$_SESSION['SadSevenTagged']."',
        '".$_SESSION['SadEight']."',
        '".$_SESSION['SadEightTagged']."',
        '".$_SESSION['AngryOne']."',
        '".$_SESSION['AngryOneTagged']."',
        '".$_SESSION['AngryTwo']."',
        '".$_SESSION['AngryTwoTagged']."',
        '".$_SESSION['AngryThree']."',
        '".$_SESSION['AngryThreeTagged']."',
        '".$_SESSION['AngryFour']."',
        '".$_SESSION['AngryFourTagged']."',
        '".$_SESSION['AngryFive']."',
        '".$_SESSION['AngryFiveTagged']."',
        '".$_SESSION['AngrySix']."',
        '".$_SESSION['AngrySixTagged']."',
        '".$_SESSION['AngrySeven']."',
        '".$_SESSION['AngrySevenTagged']."',
        '".$_SESSION['AngryEight']."',
        '".$_SESSION['AngryEightTagged']."',
        '".$_SESSION['ScaredOne']."',
        '".$_SESSION['ScaredOneTagged']."',
        '".$_SESSION['ScaredTwo']."',
        '".$_SESSION['ScaredTwoTagged']."',
        '".$_SESSION['ScaredThree']."',
        '".$_SESSION['ScaredThreeTagged']."',
        '".$_SESSION['ScaredFour']."',
        '".$_SESSION['ScaredFourTagged']."',
        '".$_SESSION['ScaredFive']."',
        '".$_SESSION['ScaredFiveTagged']."',
        '".$_SESSION['ScaredSix']."',
        '".$_SESSION['ScaredSixTagged']."',
        '".$_SESSION['ScaredSeven']."',
        '".$_SESSION['ScaredSevenTagged']."',
        '".$_SESSION['ScaredEight']."',
        '".$_SESSION['ScaredEightTagged']."',
        '".$_SESSION['SurprisedOne']."',
        '".$_SESSION['SurprisedOneTagged']."',
        '".$_SESSION['SurprisedTwo']."',
        '".$_SESSION['SurprisedTwoTagged']."',
        '".$_SESSION['SurprisedThree']."',
        '".$_SESSION['SurprisedThreeTagged']."',
        '".$_SESSION['SurprisedFour']."',
        '".$_SESSION['SurprisedFourTagged']."',
        '".$_SESSION['SurprisedFive']."',
        '".$_SESSION['SurprisedFiveTagged']."',
        '".$_SESSION['SurprisedSix']."',
        '".$_SESSION['SurprisedSixTagged']."',
        '".$_SESSION['SurprisedSeven']."',
        '".$_SESSION['SurprisedSevenTagged']."',
        '".$_SESSION['SurprisedEight']."',
        '".$_SESSION['SurprisedEightTagged']."',
        '".$_SESSION['FeelHappyAfter']."',
        '".$_SESSION['FeelSadAfter']."',
        '".$_SESSION['FeelAngryAfter']."',
        '".$_SESSION['FeelScaredAfter']."',
        '".$_SESSION['FeelSurprisedAfter']."')";

    if (mysqli_query($db, $sql)) {
        echo "Successfully inserted " . mysqli_affected_rows($db) . " rows";
    } else {
        echo "Error occurred: " . mysqli_error($db);
    }

?> 

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>FACES</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Thank You!</h1>
</body>
</html>